import type { Config } from "tailwindcss"

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        // Custom colors based on the reference image
        dark: "#121212",
        "dark-light": "#1e1e1e",
        cream: "#f8f4e3",
        green: "#00c16e",
        "green-dark": "#00a15a",
        blue: "#00b4d8",
        "blue-dark": "#0096b4",
        pink: "#ff6b95",
        "pink-dark": "#ff4778",
        yellow: "#ffc857",
        "yellow-dark": "#ffb624",
        orange: "#ff7849",
        "orange-dark": "#ff5a1f",
        red: "#e63946",
        "red-dark": "#d62836",
        purple: "#9d4edd",
        "purple-dark": "#8a2be2",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
        pulse: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        fadeIn: "fadeIn 0.5s ease-out",
        float: "float 3s ease-in-out infinite",
        pulse: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
    },
  },
  safelist: [
    // Add color variations that might be used dynamically
    "bg-red",
    "bg-red/10",
    "bg-red/20",
    "bg-red/30",
    "bg-red/50",
    "bg-red/80",
    "bg-red-dark",
    "bg-red-dark/30",
    "bg-red-dark/50",
    "bg-red-dark/70",

    "bg-blue",
    "bg-blue/10",
    "bg-blue/20",
    "bg-blue/30",
    "bg-blue/50",
    "bg-blue/80",
    "bg-blue-dark",
    "bg-blue-dark/30",
    "bg-blue-dark/50",
    "bg-blue-dark/70",

    "bg-green",
    "bg-green/10",
    "bg-green/20",
    "bg-green/30",
    "bg-green/50",
    "bg-green/80",
    "bg-green-dark",
    "bg-green-dark/30",
    "bg-green-dark/50",
    "bg-green-dark/70",

    "bg-yellow",
    "bg-yellow/10",
    "bg-yellow/20",
    "bg-yellow/30",
    "bg-yellow/50",
    "bg-yellow/80",
    "bg-yellow-dark",
    "bg-yellow-dark/30",
    "bg-yellow-dark/50",
    "bg-yellow-dark/70",

    "bg-pink",
    "bg-pink/10",
    "bg-pink/20",
    "bg-pink/30",
    "bg-pink/50",
    "bg-pink/80",
    "bg-pink-dark",
    "bg-pink-dark/30",
    "bg-pink-dark/50",
    "bg-pink-dark/70",

    "bg-purple",
    "bg-purple/10",
    "bg-purple/20",
    "bg-purple/30",
    "bg-purple/50",
    "bg-purple/80",
    "bg-purple-dark",
    "bg-purple-dark/30",
    "bg-purple-dark/50",
    "bg-purple-dark/70",

    "bg-orange",
    "bg-orange/10",
    "bg-orange/20",
    "bg-orange/30",
    "bg-orange/50",
    "bg-orange/80",
    "bg-orange-dark",
    "bg-orange-dark/30",
    "bg-orange-dark/50",
    "bg-orange-dark/70",

    "text-red",
    "text-blue",
    "text-green",
    "text-yellow",
    "text-pink",
    "text-purple",
    "text-orange",
    "text-white",
    "text-dark",

    "border-red",
    "border-red/10",
    "border-red/20",
    "border-red/30",
    "border-red/50",
    "border-red/80",
    "border-red-dark",
    "border-red-dark/50",

    "border-blue",
    "border-blue/10",
    "border-blue/20",
    "border-blue/30",
    "border-blue/50",
    "border-blue/80",
    "border-blue-dark",
    "border-blue-dark/50",

    "border-green",
    "border-green/10",
    "border-green/20",
    "border-green/30",
    "border-green/50",
    "border-green/80",
    "border-green-dark",
    "border-green-dark/50",

    "border-yellow",
    "border-yellow/10",
    "border-yellow/20",
    "border-yellow/30",
    "border-yellow/50",
    "border-yellow/80",
    "border-yellow-dark",
    "border-yellow-dark/50",

    "border-pink",
    "border-pink/10",
    "border-pink/20",
    "border-pink/30",
    "border-pink/50",
    "border-pink/80",
    "border-pink-dark",
    "border-pink-dark/50",

    "border-purple",
    "border-purple/10",
    "border-purple/20",
    "border-purple/30",
    "border-purple/50",
    "border-purple/80",
    "border-purple-dark",
    "border-purple-dark/50",

    "border-orange",
    "border-orange/10",
    "border-orange/20",
    "border-orange/30",
    "border-orange/50",
    "border-orange/80",
    "border-orange-dark",
    "border-orange-dark/50",

    "hover:bg-red",
    "hover:bg-red/10",
    "hover:bg-red/20",
    "hover:bg-red/30",
    "hover:bg-red/50",
    "hover:bg-red/80",
    "hover:bg-blue",
    "hover:bg-blue/10",
    "hover:bg-blue/20",
    "hover:bg-blue/30",
    "hover:bg-blue/50",
    "hover:bg-blue/80",
    "hover:bg-green",
    "hover:bg-green/10",
    "hover:bg-green/20",
    "hover:bg-green/30",
    "hover:bg-green/50",
    "hover:bg-green/80",
    "hover:bg-yellow",
    "hover:bg-yellow/10",
    "hover:bg-yellow/20",
    "hover:bg-yellow/30",
    "hover:bg-yellow/50",
    "hover:bg-yellow/80",
    "hover:bg-pink",
    "hover:bg-pink/10",
    "hover:bg-pink/20",
    "hover:bg-pink/30",
    "hover:bg-pink/50",
    "hover:bg-pink/80",
    "hover:bg-purple",
    "hover:bg-purple/10",
    "hover:bg-purple/20",
    "hover:bg-purple/30",
    "hover:bg-purple/50",
    "hover:bg-purple/80",
    "hover:bg-orange",
    "hover:bg-orange/10",
    "hover:bg-orange/20",
    "hover:bg-orange/30",
    "hover:bg-orange/50",
    "hover:bg-orange/80",

    "hover:border-red",
    "hover:border-blue",
    "hover:border-green",
    "hover:border-yellow",
    "hover:border-pink",
    "hover:border-purple",
    "hover:border-orange",

    "hover:shadow-red/20",
    "hover:shadow-blue/20",
    "hover:shadow-green/20",
    "hover:shadow-yellow/20",
    "hover:shadow-pink/20",
    "hover:shadow-purple/20",
    "hover:shadow-orange/20",
  ],
  plugins: [],
}
export default config
